### PR TITLE
imp: investigate why upgrade-client halts `gaiad`

### LINKED ISSUE #177: upgrade-client before token-transfer fails integration test
This was overlooked before as upgrade-client and token-transfer were being executed in parallel.

This issue came up while adding recover-client tests from #176

### PR DESCRIPTION
**Pull request by rnbguy**
Closes #177 

- updates CI dependencies (gaia, hermes, cometbft, grpcurl, rust toolchain).
- in case of failure, prints last 200 lines from the logs from gaia, basecoin, cometbft.
- uses github workflow concurrency option.
- uses actions-rust-lang/setup-rust-toolchain to setup rust.
- implements `HealthService::get_syncing`.
- rename `one-chain` script to `one-chain.sh`.

### CODE REVIEW

**Comment by rnbguy** [comment]
Looks like, there is consensus failure at `gaiad` chain (`ibc-0`)

```
UPGRADE "plan" NEEDED at height: 144:  module=consensus stack=goroutine 132 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
	github.com/tendermint/tendermint@v0.34.21/consensus/state.go:732 +0x4c
panic({0x1949de0, 0xc003c99d30})
	runtime/panic.go:838 +0x207
...
```

**Comment by rnbguy** [comment]
Latest changes now [log the error directly on workflow](https://github.com/informalsystems/basecoin-rs/actions/runs/8803587744/job/24162067996?pr=178#step:14:1812).

**Comment by rnbguy** [comment]
The error is coming from [cosmos/cosmos-sdk/x/upgrade/keeper/abci.go#L79](https://github.com/cosmos/cosmos-sdk/blob/843fc134df0bc090c29d8c2958704568b65ca5ba/x/upgrade/keeper/abci.go#L79).

**Comment by rnbguy** [comment]
We need to recompile the binary with a handler for the _plan_. I think it'll be fine to cancel the software upgrade somehow. There is a subcommand `gaiad tx upgrade cancel-software-upgrade` - but it doesn't work.

**Comment by rnbguy** [comment]
It looks like the `upgrade-client` test is meant to halt `gaiad` after the upgrade height. So, this script must be executed at the end of our e2e tests.

We may only run the grpc-service after it, as it doesn't involves `gaiad`.

**Review by seanchen1991 — APPROVED** [review]
Looks good. Makes sense moving the upgrade client test to the end of the testing order 👍

**Pull request merged**
